---
- name: "Create datasaker local directory"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{datasaker_docker_user}}"
    group: "{{datasaker_docker_group}}"
    mode: '0755'
  with_items:
    - "{{ datasaker_docker_path }}/agent/dsk-maria-agent"

- name: "Create agent config"
  ansible.builtin.file:
    path: "{{ datasaker_docker_path }}/dsk-docker-maria-config.yml"
    state: touch

- name: "Setting dsk-maria-agent config"
  template:
    src: docker-maria-agent-config.yml.j2
    dest: "{{ datasaker_docker_path }}/dsk-docker-maria-config.yml"

- name: "Run dsk-maria-agent container"
  docker_container:
    name: dsk-docker-maria-agent
    image: "datasaker/dsk-maria-agent:{{ maria_agent_image_tag }}"
    state: started
    restart_policy: "{{ maria_agent_restart_policy }}"
    detach: true
    env:
      DKS_LOG_LEVEL: "info"
    volumes:
      - "{{ datasaker_docker_path }}:/var/datasaker/"
      - "{{ datasaker_docker_global_config }}:/etc/datasaker/global-config.yml:ro"
      - "{{ datasaker_docker_path }}/dsk-docker-maria-config.yml:/etc/datasaker/dsk-maria-agent/agent-config.yml:ro"