---
- name: Remove Datasaker Log Directory
  ansible.builtin.file:
    path: "/var/log/datasaker/{{ item }}"
    state: absent
  with_items:
    - "{{ datasaker_agents }}"

- name: Remove Datasaker Agent Directory
  ansible.builtin.file:
    path: "/etc/datasaker/{{ item }}"
    state: absent
  with_items:
    - "{{ datasaker_agents }}"

- name: Stop agent service
  service:
    name: "{{ item }}"
    enabled: true
    state: stopped
  with_items:
    - "{{ datasaker_agents }}"
  ignore_errors: true

- name: "Uninstall datasaker agent"
  apt:
    name: "{{ item }}"
    state: absent
    update_cache: yes
  with_items:
    - "{{ datasaker_agents }}"
  ignore_errors: true

- name: Remove Datasaker Agent Directory
  ansible.builtin.file:
    path: "/etc/datasaker/{{ item }}"
    state: absent
  with_items:
    - "{{ datasaker_agents }}"

- name: Remove Datasaker All Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/datasaker
    - /var/log/datasaker
    - /var/datasaker
    - ~/.datasaker
    - "{{ apt_sources_list }}"
    - "{{ apt_trusted_d_keyring }}"
    - "{{ apt_usr_share_keyring }}"
  when: datasaker_clean == True

- name: "Remove datasaker_docker_user"
  ansible.builtin.user:
    name: "{{datasaker_docker_user}}"
    state: absent
  when: datasaker_clean == True
  ignore_errors: yes

- name: "Remove datasaker_docker_group"
  ansible.builtin.group:
    name: "{{datasaker_docker_group}}"
    state: absent
  when: datasaker_clean == True
  ignore_errors: yes