---
- name: Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: True

- name: Restart dsk-trace-agent service
  ansible.builtin.systemd:
    name: dsk-trace-agent
    enabled: true
    state: restarted

- name: Restart dsk-node-agent service
  ansible.builtin.systemd:
    name: dsk-node-agent
    enabled: true
    state: restarted

- name: Restart dsk-log-agent service
  ansible.builtin.systemd:
    name: dsk-log-agent
    enabled: true
    state: restarted

- name: Restart dsk-postgres-agent service
  ansible.builtin.systemd:
    name: dsk-postgres-agent
    enabled: true
    state: restarted

- name: Restart dsk-plan-postgres-agent service
  ansible.builtin.systemd:
    name: dsk-plan-postgres-agent
    enabled: true
    state: restarted    

- name: Restart dsk-mysql-agent service
  ansible.builtin.systemd:
    name: dsk-mysql-agent
    enabled: true
    state: restarted

- name: Restart dsk-plan-mysql-agent service
  ansible.builtin.systemd:
    name: dsk-plan-mysql-agent
    enabled: true
    state: restarted   

- name: Restart dsk-maria-agent service
  ansible.builtin.systemd:
    name: dsk-maria-agent
    enabled: true
    state: restarted

- name: Restart dsk-plan-maria-agent service
  ansible.builtin.systemd:
    name: dsk-plan-maria-agent
    enabled: true
    state: restarted

- name: Restart dsk-redis-agent service
  ansible.builtin.systemd:
    name: dsk-redis-agent
    enabled: true
    state: restarted

- name: Restart dsk-cloudwatch-agent service
  ansible.builtin.systemd:
    name: dsk-cloudwatch-agent
    enabled: true
    state: restarted